services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    network_mode: service:client
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
