# Docker Compose file paths for different services
# You can override these paths by defining them in the environment before running make
# If you want to add more services, create their directories and docker-compose files, then add their paths here
FTP-PATH =? ./ftp/docker-compose.yml
DNS-PATH =? ./dns/docker-compose.yml
SMTP-PATH =? ./smtp/docker-compose.yml
HTTP-PATH =? ./http/docker-compose.yml
CLIENT-PATH =? ./client/docker-compose.yml

# The master docker-compose file that includes all services
MASTER-PATH ?= ./docker-compose.yml

up:
	docker-compose -f $(MASTER-PATH) up -d

down:
	docker-compose -f $(MASTER-PATH) down

ftp-up:
	docker-compose -f $(FTP-PATH) up -d

ftp-down:
	docker-compose -f $(FTP-PATH) down

dns-up:
	docker-compose -f $(DNS-PATH) up -d

dns-down:
	docker-compose -f $(DNS-PATH) down

smtp-up:
	docker-compose -f $(SMTP-PATH) up -d

smtp-down:
	docker-compose -f $(SMTP-PATH) down

http-up:
	docker-compose -f $(HTTP-PATH) up -d

http-down:
	docker-compose -f $(HTTP-PATH) down

client-up:
	docker-compose -f $(CLIENT-PATH) up -d
	
client-down:
	docker-compose -f $(CLIENT-PATH) down